### ISSUE TITLE
No Issue: How do i get a public address.

### ISSUE THREAD

**Issue by CTJaeger** [griffo-io/tron.net#2]
Hello. 

How do i get a public address with: Tron.Net.Crypto.ECKey.FromPrivateHexString("ABC")

Greets Marco

**Comment by EnjoX** [comment]
Hi
Like this:

    var address = WalletAddress.MainNetWalletAddress(ECKey.FromPrivateHexString("8e812436a0e3323166e1f0e8ba79e19e217b2c4a53c970d4cca0"));
    string addressString = address.ToString();

If you want the same as in TronLink you have to qait for my pull request
