### ISSUE TITLE
Wallet implementation creates new GRPC client and channel for each call

### ISSUE THREAD

**Issue by maincoon** [griffo-io/tron.net#7]
GRPC recommends reuse channels and it's calls also thread safe. Current implementation of IWallet at https://github.com/griffo-io/tron.net/blob/master/src/Tron.Net.Client/Wallet.cs violates this recomandations and creates new client for each call. Backend with this code starts to absorb resources (CPU and memory) while using wallet for some long time. Finally I've created own IWallet available in attach.

Thank you.
[TRONClient.cs.txt](https://github.com/griffo-io/tron.net/files/4044871/TRONClient.cs.txt)

**Comment by dariogriffo** [comment]
I will see if I can do some work this weekend updating the library. Sorry, been away for a while

**Comment by wasimjee** [comment]
@maincoon 

Do u have the codes updated in github?

i am unable to connect and access the Wallet. Any Help.

**Comment by dariogriffo** [comment]
Code is updated now, there is only 1 instance of the channel created.
Ideally you want the GRPC Channel factory to be a singleton created by your IoC framework
