### ISSUE TITLE
There is an error in Tron.Net.Client.nuspec file

### ISSUE THREAD

**Issue by maincoon** [griffo-io/tron.net#9]
I believe dependencies should point to Grpc.Core not Google.Core package. Because of this error nuget package available via nuget.org is not usable unfortunalely.

Thank you.
[Tron.Net.Client.nuspec.diff.txt](https://github.com/griffo-io/tron.net/files/4052862/Tron.Net.Client.nuspec.diff.txt)

**Comment by dariogriffo** [comment]
Thanks, it has been fixed and pushed now.
You can create a PR if you want too next time!
